### ISSUE TITLE
tns-media-gen: command not found

### ISSUE THREAD

**Issue by davorpeic** [hypery2k/nativescript-media-generator#13]
I just tried to install this modules, but can't get to run it, I tried installing it first globally as instructed, then I tried to install it locally in my project, get the same error.

I run node 6.7.0 and I'm using https://github.com/creationix/nvm to manage my node versions.

Any ideas?
thanks

**Comment by hypery2k** [comment]
thanks for reporting the issue, will release a new version

**Comment by hypery2k** [comment]
version 0.2.4 ist now available

**Comment by davorpeic** [comment]
Thanks, confirming this fixes the command not found issue
